proxmox_url             = "https://192.168.1.68:8006/api2/json"
proxmox_username        = "terraform@pve!terratoken"
proxmox_token           = "e5be47e8-308c-413c-a3b8-ac2b722d64af"
proxmox_skip_tls_verify = "true"
proxmox_node            = "windows-perso"
proxmox_pool            = "TEMPLATE"
proxmox_iso_storage     = "local"
proxmox_vm_storage      = "local-lvm"
