proxmox_url             = "PROXM_API_URL"
proxmox_username        = "terraform@pve!terratoken"
proxmox_token           = "3ee3f15f-12a4-4b1a-8809-1e07a4af880f"
proxmox_skip_tls_verify = "true"
proxmox_node            = "windows-perso"
proxmox_pool            = "TEMPLATE"
proxmox_iso_storage     = "local"
proxmox_vm_storage      = "local-lvm"
