proxmox_url             = "PROXM_API_URL"
proxmox_username        = "terraform@pve!terratoken"
proxmox_token           = "9c2f97a9-d817-4bbf-b4ee-33a897b6f1bf"
proxmox_skip_tls_verify = "true"
proxmox_node            = "windows-perso"
proxmox_pool            = "TEMPLATE"
proxmox_iso_storage     = "local"
proxmox_vm_storage      = "local-lvm"
